# Generated by Django 4.0.5 on 2022-06-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('autor', models.CharField(max_length=200)),
                ('fecha_de_cargar', models.DateField(auto_now=True)),
            ],
        ),
    ]
